version: '3'
services:
  web:
    build: python-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - pg
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=pg

  pg:
    build:
      context: ./
      dockerfile: postgres/Dockerfile
    restart: always
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: p0stgres!
      POSTGRES_PASSWORD: password
    #   POSTGRES_USER: postgres
    # volumes:
    #   - ./init:/docker-entrypoint-initdb.d
    command: /bin/bash /migrate.sh
    ports:
      - '5432:5432'
      # run container its runs entrypoint first THEN CMD (always in this order)
      # postgres official has its own entrypoint and CMD and we are overwritign it maybe
      # we are overriding the ENTRYPOINT
